server:
  port: 1234

build.name: @project.name@
build.version: @project.version@

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/abctech
    username: fiap
    password: Fiap1234
  jpa:
    hibernate:
      ddl-auto: create-drop
